const PatientList = [
  {
    personal: {
      FirstName: "kishore",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "01-06-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2022KR0106",
      token: "2001",
    },
    appointment: {
      appointment: "yes",
      date: "20-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "no",
      amount: "2000",
      paymentType: "card",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2022KR0303",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "20-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "kishore",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "01-06-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2022KR0404",
      token: "2003",
    },
    appointment: {
      appointment: "yes",
      date: "20-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "no",
      amount: "3000",
      paymentType: "cash",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2022KR0309",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "20-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2022KRj803",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "20-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD20289R0303",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "20-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2078KR0303",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "20-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2kj7KR0303",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "20-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD20jkkR0303",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "23-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2022de0303",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "21-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "21-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2022Kpli03",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "18-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD202287g303",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "16-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2022iu0303",
      token: "2002",
    },
    appointment: {
      appointment: "no",
      date: "17-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
  {
    personal: {
      FirstName: "deepika",
      LastName: "Rajavel",
      Gender: "male",
      DoB: "04-04-2002",
      Age: "20",
      Mobile: "6383439137",
      MartialStatus: "Single",
      FatherName: "Rajavel",
      Email: "kishorerajavel1@gmail.com",
      Occupation: "Developer",
      Address: "7/182,Coimbatore",
      District: "coimbatore",
      Country: "India",
      State: "Tamilnadu",
      Pincode: "641113",
    },
    guardian: {
      FirstName: "Deepika",
      LastName: "Rajavel",
      Mobile: "8095466851",
      Relationship: "sister",
      Address: "7/182,coimbatore",
    },
    official: {
      tag: "MD2022Klo303",
      token: "2002",
    },
    appointment: {
      appointment: "yes",
      date: "16-8-2022",
      time: "10-pm",
      purpose: "fever",
    },
    billing: {
      billing: "",
      amount: "",
      paymentType: "",
    },
  },
];

export default PatientList;
